version: '3.7'

networks:
    docker_registry:
        driver: bridge

volumes:
  registry-data: # the real name will be <parent-folder-name>_registry-data (dash '-' int he folder name will be removed). eg. authenticatedregistry_registry-data
    driver: local

services:
  auth:
    image: ${DOCKER_AUTH_IMAGE}
    container_name: auth
    ports:
      - 5001:5001
    volumes:
      - ./config:/config:ro
      - ./certs:/certs
    restart: always
    command: --v=2 --alsologtostderr /config/auth_config.yml
    networks:
      - docker_registry  

  registry:
    image: ${REGISTRY_IMAGE}
    container_name: registry
    ports:
      - 5000:5000
    volumes:
      - ./certs:/certs
      - registry-data:/var/lib/registry
    restart: always
    networks:
      - docker_registry
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
      - REGISTRY_STORAGE_DELETE_ENABLED=true

      - REGISTRY_AUTH=token
      - REGISTRY_AUTH_TOKEN_REALM=https://$DOMAIN/authorization/auth # the authentication server URI
      - REGISTRY_AUTH_TOKEN_SERVICE="Docker Registr"
      - REGISTRY_AUTH_TOKEN_ISSUER="Docker Registry Auth Server" # Should be the same as token.issuer from authenticated-registry/config/auth_config.yml
      - REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE=/certs/docker_auth.pem
