
# Server settings.
# https://github.com/cesanta/docker_auth/blob/master/examples/reference.yml
server: 
  # Address to listen on.
  addr: ":5001"

  # This is listening on HTTP only
  # If neither certificate+key or letsencrypt are configured, the listener does not use TLS.

token:  # Settings for the tokens.
  issuer: "Docker Registry Auth Server"  # Must match issuer in the Registry config.
  expiration: 900

  # Token must be signed by a certificate that registry trusts, i.e. by a certificate to which a trust chain
  # can be constructed from one of the certificates in registry's auth.token.rootcertbundle.
  # If not specified, server's TLS certificate and key are used.
  certificate: "/certs/docker_auth.pem"
  key: "/certs/docker_auth.key"
  
# Static user map.
users:
  # Password is specified as a BCrypt hash. Use htpasswd -B to generate.
  "admin":
    password: "$2y$05$gpCDFX7TJQnNbsBmXNgHduXFwoF55geNZPTKk4AgyZEo8CL/Gqdq6"
  "jgsqware": # my user
    password: "$2y$05$NbdXlgQWKZBy6F2zBiX.Ue.k4ui/7yVUYt.ysxqymVi4EtAeduaga"

acl:
  # Admin has full access to everything.
  - match: {account: "admin"}
    actions: ["*"]

  # Users have full right on their repository
  - match: {account: "/.+/", name: "${account}/*"}
    actions: ["*"]

  # Access is denied by default.
